name: Go

on:
  push:
    tags:
    - v*
    branches: 
    - ci/*

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
      BUILD_FLAGS: -trimpath -ldflags "-w -s" -o
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Make release dir
      run: mkdir release
      
    - name: Build linux release
      env:
        GOOS: linux
      run: |
        GOARCH=amd64 go build ${{ env.BUILD_FLAGS }} release/yarx_linux_amd64 ./cmd/yarx
        GOARCH=386   go build ${{ env.BUILD_FLAGS }} release/yarx_linux_386   ./cmd/yarx
        GOARCH=arm64 go build ${{ env.BUILD_FLAGS }} release/yarx_linux_arm64 ./cmd/yarx
        
    - name: Build windows release
      env:
        GOOS: windows
      run: |
        GOARCH=amd64 go build ${{ env.BUILD_FLAGS }} release/yarx_windows_amd64.exe ./cmd/yarx
        GOARCH=386   go build ${{ env.BUILD_FLAGS }} release/yarx_windows_386.exe   ./cmd/yarx
        
    - name: Build darwin release
      env:
        GOOS: darwin
      run: |
        GOARCH=amd64 go build ${{ env.BUILD_FLAGS }} release/yarx_darwin_amd64 ./cmd/yarx
        GOARCH=arm64 go build ${{ env.BUILD_FLAGS }} release/yarx_darwin_arm64 ./cmd/yarx

    - name: Upload release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        name: "v0.0.1"
        tag_name: "v0.0.1"
        files: |
          release/yarx_linux_amd64
          release/yarx_linux_386
          release/yarx_linux_arm64
          release/yarx_windows_amd64.exe
          release/yarx_windows_386.exe
          release/yarx_darwin_amd64
          release/yarx_darwin_arm64
